---
name: CI
'on':
  pull_request:
  push:

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot' # See 'Supported distributions' for available options
          java-version: '15.0.1'
          cache: 'gradle'

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          gradle-version: 7.6.1

      - name: Execute build
        run: gradle build -x test

      - name: Execute runtime
        run: gradle runtime

      - name: Execute jpackage
        run: gradle --debug jpackage

      - name: Upload DEB as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: bigdata-file-viewer-jdk11-ubuntu-latest-deb
          path: build/jpackage/*.deb
