---
name: CI
'on':
  pull_request:
  push:

jobs:
  linux:
    name: Build linux package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot' # See 'Supported distributions' for available options
          java-version: '15.0.1'
          cache: 'gradle'

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          gradle-version: 7.6.3
          cache-overwrite-existing: true

      - name: cache build folders
        uses: actions/cache@v3
        with:
          path: |
            ./bigdata-file-viewer/build
            ./build
            ~/.gradle/caches
            ~/.gradle/wrapper
            $HOME/.m2/repository
            ~/.m2/repository
            ./.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
            gradle-${{ runner.os }}-
            gradle-${{ runner.os }}
            gradle-

      - name: Execute build
        run: gradle build -x test

      - name: Execute runtime
        run: gradle runtime

      - name: Execute jpackage
        run: gradle --info --stacktrace jpackage

      - name: Upload DEB as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: bigdata-file-viewer-jdk15-ubuntu-latest.deb
          path: build/jpackage/*.deb

  mac:
    name: Build mac package
    runs-on: macos-12
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot' # See 'Supported distributions' for available options
          java-version: '15.0.1'
          cache: 'gradle'

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          gradle-version: 7.6.3
          cache-overwrite-existing: true

      - name: cache build folders
        uses: actions/cache@v3
        with:
          path: |
            ./bigdata-file-viewer/build
            ./build
            ~/.gradle/caches
            ~/.gradle/wrapper
            $HOME/.m2/repository
            ~/.m2/repository
            ./.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
            gradle-${{ runner.os }}-
            gradle-${{ runner.os }}
            gradle-

      - name: Execute build
        run: gradle build -x test

      - name: Execute runtime
        run: gradle runtime

      - name: Execute jpackage
        run: gradle --info --stacktrace jpackage

      - name: Upload DEB as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: bigdata-file-viewer-jdk15-ubuntu-latest.dmg
          path: build/jpackage/*.dmg
