---
name: CI
'on':
  pull_request:
  push:

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica' # See 'Supported distributions' for available options
          java-version: '11'
          java-package: 'jdk+fx'
          cache: 'gradle'

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          gradle-version: 7.6.1

      - name: Execute build
        run: gradle --info --stacktrace build

      - name: Execute runtime
        run: gradle --info --stacktrace runtime

      - name: Execute jpackage
        run: gradle --info --stacktrace jpackage

      - uses: actions/upload-artifact@v1
        with:
          name: Linux binaries
          path: build/libs
