---
name: CI
'on':
  pull_request:
  push:

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'gradle'

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          gradle-version: 7.6.1

      - uses: actions/upload-artifact@v1
        with:
          name: Linux binaries
          path: build/libs
